{
 "title": "Sign Up",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Web", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTP OK Responses",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total{code=\"200\", job=\"web\"}[5m])) without(host, instance, method, action, controller, exported_instance, code)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "HTTP Error Responses",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total{code=\"500\", job=\"web\"}[5m])) without(host, instance, method, action, controller, exported_instance, code)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 6, "x": 14, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_bucket{job=\"web\"}[5m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "CPU /s",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 1 },
   "targets": [
    {
     "expr": "sum(process_cpu_seconds_total{job=\"web\"})"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 1 },
   "targets": [
    {
     "expr": "sum(dotnet_total_memory_bytes{job=\"web\"})"
    }
   ]
  },
  {
   "title": "Versions",
   "type": "table",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 5 },
   "targets": [
    {
     "expr": "app_info{job=\"web\"}"
    }
   ]
  },
  { "title": "API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "HTTP OK Responses",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total{code=\"200\", job=\"api\"}[5m])) without(host, instance, method, action, controller, exported_instance, code)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "HTTP Error Responses",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total{code=\"500\", job=\"api\"}[5m])) without(host, instance, method, action, controller, exported_instance, code)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 6, "x": 14, "y": 9 },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_bucket{job=\"api\"}[5m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "CPU /s",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 9 },
   "targets": [
    {
     "expr": "sum(process_cpu_seconds_total{job=\"web\"})"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 9 },
   "targets": [
    {
     "expr": "sum(dotnet_total_memory_bytes{job=\"api\"})"
    }
   ]
  },
  {
   "title": "Versions",
   "type": "table",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 13 },
   "targets": [
    {
     "expr": "app_info{job=\"api\"}"
    }
   ]
  },
  { "title": "Message Handlers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Events Received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " sum(rate(SaveHandler_Events{status=\"received\"}[1m])) without(host, instance, job)",
     "legendFormat": "Save Events"
    },
    {
     "expr": "sum(rate(IndexHandler_Events{status=\"received\"}[1m])) without(host, instance, job)",
     "legendFormat": "Index Events"
    }
   ]
  },
  {
   "title": "Events Processed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " sum(rate(SaveHandler_Events{status=\"processed\"}[1m])) without(host, instance, job)",
     "legendFormat": "Save Events"
    },
    {
     "expr": "sum(rate(IndexHandler_Events{status=\"processed\"}[1m])) without(host, instance, job)",
     "legendFormat": "Index Events"
    }
   ]
  },
  {
   "title": "Events Failed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " sum(rate(SaveHandler_Events{status=\"failed\"}[1m])) without(host, instance, job)",
     "legendFormat": "Save Events"
    },
    {
     "expr": "sum(rate(IndexHandler_Events{status=\"failed\"}[1m])) without(host, instance, job)",
     "legendFormat": "Index Events"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(dotnet_total_memory_bytes{job=~\"index-handler|save-handler\"}) without(instance)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": ".NET CPU Time (s)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(process_cpu_seconds_total{job=~\"index-handler|save-handler\"}) without(instance)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Versions",
   "type": "table",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 17 },
   "targets": [
    {
     "expr": "app_info{job=~\"index-handler|save-handler\"}"
    }
   ]
  }
 ]
}