# v5 adds self-service analytics with Elastcisearch and Kibana
version: '3.7'

services:
  
  signup-db:
    image: dak4dotnet/sql-server:2017
    environment:
      - sa_password=DockerCon!!!
    networks:
      - app-net

  signup-web:
    image: dak4dotnet/signup-web:v2
    environment: 
      - Dependencies:IReferenceDataLoader=SignUp.Web.ReferenceData.ApiReferenceDataLoader
      - ReferenceDataApi:Url=http://reference-data-api/api
      - Dependencies:IProspectSaveHandler=SignUp.Web.ProspectSave.AsynchronousProspectSaveHandler
    labels:
      - "traefik.frontend.rule=PathPrefix:/app"
      - "traefik.frontend.priority=30"
    depends_on:
      - signup-db
      - reference-data-api
    networks:
      - app-net

  homepage:
    image: dak4dotnet/homepage
    labels:
      - "traefik.frontend.rule=PathPrefix:/"
      - "traefik.frontend.priority=10"
    networks:
      - app-net

  proxy:
    image: dak4dotnet/reverse-proxy
    command: --docker --docker.endpoint=npipe:////./pipe/docker_engine --docker.watch --api
    isolation: process
    ports:
      - "8020:80"
      - "8080:8080"
    volumes:
      - type: npipe
        source: \\.\pipe\docker_engine
        target: \\.\pipe\docker_engine      
    networks:
      - app-net

  reference-data-api:
    image: dak4dotnet/reference-data-api
    environment: 
      - ConnectionStrings:SignUpDb=Server=signup-db;Database=SignUp;User Id=sa;Password=DockerCon!!!
    labels:
      - "traefik.frontend.rule=PathPrefix:/api"
      - "traefik.frontend.priority=20"
    depends_on:
      - signup-db
    networks:
      - app-net

  message-queue:
    image: nats:2.1.7-nanoserver-1809
    networks:
      - app-net

  signup-save-handler:
    image: dak4dotnet/save-handler
    depends_on:
      - signup-db
      - message-queue
    networks:
      - app-net

  signup-index-handler:
    image: dak4dotnet/index-handler
    depends_on:
      - elasticsearch
      - message-queue
    networks:
      - app-net

  elasticsearch:
    image: dak4dotnet/elasticsearch
    networks:
      - app-net

  kibana:
    image: dak4dotnet/kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - app-net

networks:
  app-net:
    external:
      name: nat